version: 0.1.x.{build}
skip_commits:
  message: /^\(?doc|travis\)?.*/
clone_depth: 10
init:
- SET
- 'echo System architecture: %PLATFORM%'
- 'echo %APPVEYOR_REPO_NAME%'

environment:
  ROLE_NAME: ansible-role-windows-admin-center
  winrm_user: ansible-ci
  winrm_password: Passw0rd!1
  APPVEYOR_RDP_PASSWORD: Passw0rd!1

  matrix:
  - ANSIBLE_VERSION: "2.9.2"
    ANSIBLE_EXTRA_VARS:
  - ANSIBLE_VERSION: "2.8.7"
    ANSIBLE_EXTRA_VARS:
  - ANSIBLE_VERSION: "2.7.15"
    ANSIBLE_EXTRA_VARS:
matrix:
  fast_finish: true

install:
- ps: >-
    net user /Y /add $env:winrm_user $env:winrm_password
    net localgroup administrators $env:winrm_user /add
    $url = "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
    $file = "$env:temp\ConfigureRemotingForAnsible.ps1"
    (New-Object -TypeName System.Net.WebClient).DownloadFile($url, $file)
    powershell.exe -ExecutionPolicy ByPass -File $file
- cmd: >-
    wsl -e uname -a
    wsl -e python -m ensurepip
    wsl -e python3 -m ensurepip
    wsl -e python3 -m pip install --upgrade pip
    wsl -e python3 -m pip install pywinrm
    wsl -e python3 -m pip install ansible==%ANSIBLE_VERSION%
    wsl -e ansible --version
    wsl -e echo localhost ansible_user=$winrm_user ansible_password=$winrm_password ansible_connection=winrm
    wsl -e ls /
    wsl -e ls -l /mnt/c/
    wsl -e ls -l /mnt/c/git/%ROLE_NAME%
    wsl -e pwd
    wsl -e ansible -i /mnt/c/git/%ROLE_NAME%/tests/inventory.yml -m win_ping -vvv localhost
    wsl -e mkdir -p /etc/ansible/roles
    wsl -e cp -R /mnt/c/git/%ROLE_NAME% /etc/ansible/roles/%ROLE_NAME%

build: off
test_script:
- cmd: "wsl -e ansible-playbook -i /mnt/c/git/%ROLE_NAME%/tests/inventory.yml /mnt/c/git/%ROLE_NAME%/test/appveyor/playbook.yml -vvv $ANSIBLE_EXTRA_VARS"

for:
  - matrix:
      only:
        - SUITE: default
    after_test:
    - cmd: |
        wsl -e ansible-playbook -i /mnt/c/git/%ROLE_NAME%/tests/inventory.yml /mnt/c/git/%ROLE_NAME%/test/integration/$SUITE/default.yml $ANSIBLE_EXTRA_VARS

notifications:
- provider: Email
  to:
  - nobody@nowhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false