---

- name: Download Installer
  win_get_url:
    url: "{{ wac_download_url }}"
    dest: "{{ wac_download_path }}"
    follow_redirects: all

- name: Set Appropriate Facts
  set_fact:
    wac_args:
      - SME_PORT={{ wac_sme_port }}
      - SSL_CERTIFICATE_OPTION={{ wac_ssl_certificate_option }}
      - RESTART_WINRM=0
  when: wac_ssl_certificate_option == "generate"

- name: Set Appropriate Facts
  set_fact:
    wac_args:
      - SME_PORT={{ wac_sme_port }}
      - SSL_CERTIFICATE_OPTION={{ wac_ssl_certificate_option }}
      - SME_THUMBPRINT={{ wac_sme_thumbprint }}
      - RESTART_WINRM=0
  when: wac_ssl_certificate_option == "installed"

- name: Install WAC with Selected Options
  win_package:
    creates_path: "{{ wac_local_install_path }}"
    creates_service: Windows Admin Center
    expected_return_code: 0,3010
    arguments: "{{ wac_args }}"
    path: "{{ wac_download_path }}"
  register: wac_install

- name: Restart Server
  win_reboot:
    msg: Rebooting to Complete Windows Admin Center Installation
  when: wac_install.reboot_required == true

- name: Delete Installer
  win_file:
    path: "{{ wac_download_path }}"
    state: absent

- name: Enable Constrained Delegation
  import_tasks: delegation.yml
  when: wac_constrained_delegation_enabled == true