---
dependency:
  name: galaxy
driver:
  name: delegated
  hostname: "${VCENTER_HOST}"
  username: "${VCENTER_USR}"
  password: "${VCENTER_PSW}"
  validate_certs: true
  datacenter: SDDC-Datacenter
  folder: /CI/
  vm_username: Administrator
  vm_password: awvmware331!
  connection: winrm
  port: 5986
  winrm_transport: ntlm
  winrm_server_cert_validation: ignore
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "c1-${GIT_COMMIT}"
    template: ci-win2016x
    snapshot_src: base
    cluster: Cluster-1
    memory_mb: 8192
    cpus: 4
    datastore: WorkloadDatastore
    network:
      - name: mgmt
        ip: 10.139.5.230
        netmask: 255.255.255.0
        gateway: 10.139.5.1
        dns_servers:
        - 8.8.8.8
        - 8.8.4.4
  - name: "c2-${GIT_COMMIT}"
    template: ci-win2019x
    snapshot_src: base
    cluster: Cluster-1
    memory_mb: 8192
    cpus: 4
    datastore: WorkloadDatastore
    network:
      - name: mgmt
        ip: 10.139.5.231
        netmask: 255.255.255.0
        gateway: 10.139.5.1
        dns_servers:
        - 8.8.8.8
        - 8.8.4.4
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
  ansible_args:
    - -vvvv
  playbooks:
    create: create.yml
    converge: playbook.yml
    destroy: destroy.yml
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: default
  test_sequence:
    #- lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    # - cleanup
    # - destroy
