---
- name: Converge
  hosts: all
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_become_method: runas
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
