---
- name: Converge
  hosts: all
  vars:
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_read_timeout_sec: 120
    ansible_winrm_operation_timeout_sec: 60
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
